name: (Disabled) Deploy Static Site to GitHub Pages

on:
  # Disabled automatic triggers to avoid duplicate deployments
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Disabled Workflow Notice
        run: echo "This workflow is disabled. Use .github/workflows/pages.yml for deployments."